### ISSUE TITLE
refactor: reduce the JS lines

### ISSUE THREAD

**Issue by ghost** [muthukumarimoorthi/cyberdude-challenges#2]
Hi @muthukumarimoorthi, I saw your `yt-grabber` it was so good but still you could refactor the code to reduce the lines and make it more slick. As you can see some variables were hanging alone so concatenate them with `[0]` values directly after the split with the value.  Hope this helps! Thank you.

**Comment by muthukumarimoorthi** [comment]
@mshajid thank u for the valuable comment
